#pragma once

enum RTX_MATERIAL_TYPE {
    RTX_MATERIAL_TYPE_UNKNOWN,
    RTX_MATERIAL_TYPE_LAMBERT,
    RTX_MATERIAL_TYPE_METAL,
    RTX_MATERIAL_TYPE_EMISSIVE,
};

enum RTX_GEOMETRY_TYPE {
    RTX_GEOMETRY_TYPE_UNKNOWN,
    RTX_GEOMETRY_TYPE_STANDARD,
    RTX_GEOMETRY_TYPE_SPHERE,
};

enum RTX_CAMERA_TYPE {
    RTX_CAMERA_TYPE_UNKNOWN,
    RTX_CAMERA_TYPE_PERSPECTIVE,
    RTX_CAMERA_TYPE_ORTHOGONAL,
};